return {
    descriptions = {
        Joker = {
            j_star_notreadingallat_0 = {
                name = 'Not Reading Allat',
                text = {
                     "Press {C:green}[C]{} to cycle description (1/7)",
                     " ",
                     "{V:2}Sanity: {C:attention}#3#    {V:1}Tigermark Round: {C:attention}#5#    {V:1}Savage Tigermark Round: {C:attention}#6#{}", 
                     "{C:attention}Unrelenting Spirit: #7#    Unrelenting Spirit - Shin: #8#{}    {C:diamonds}Overheat: #9#{}",
                     "{V:4}Tremor: {C:attention}#10#{} potency, {C:attention}#11#{} count    {V:4}Burn: {C:attention}#12#{} potency, {C:attention}#13#{} count",
                     " ",
                     "Before scoring, chooses one of three skills to use and",
                     "rolls coins that give {C:red}+mult{} and {C:blue}+chips{} by the skill's power",
                     "Coins are rolled based on this Joker's {V:2}sanity",
                     "{C:inactive}(Max sanity is 45, min sanity is -45)",
                     "{V:2}Sanity{} increases after clearing a blind based on hand count",
                     "{C:inactive}(Base Value is 20, raised by 2 per hand remaining){}",
                     "{V:2}Sanity{} decreases by {C:attention}10{} after playing a hand without beating the blind",
                     "When {C:red}debuffed{}, this Joker's Coin Power is set to {C:attention}0{}", 

                },
            },

            j_star_notreadingallat_1         = { 
                name = 'Not Reading Allat',
                text = {
                    "Press {C:green}[C]{} to cycle description (2/7)",
                    " ",
                    "{C:money}Skill 1: Double Slash - Blast{} (2 Coins, 4 Base Power, +4 Coin Power)",
                    "Final Power +1 for every 4 (sum of {V:4}Burn{} and {V:4}Tremor{} on the main target) (max 3)",
                    "[I] {C:green}[On Hit]{} Inflict 1 {V:4}Tremor{}",
                    "[II] Spend 1 {V:1}Tigermark Round{}",
                    "{C:green}[On Hit]{} Inflict 2 {V:4}Tremor{}",
                    "{C:green}[On Hit]{} Inflict 2 {V:4}Burn{}",
                },
            },
            j_star_notreadingallat_2         = { 
                name = 'Not Reading Allat',
                text = {
                    "Press {C:green}[C]{} to cycle description (3/7)",
                    " ",
                    "{C:diamonds}Skill 2: Triple Slash - Blast{} (3 Coins, 4 Base Power, +4 Coin Power)",
                    "Final Power +1 for every 4 (sum of {V:4}Burn{} and {V:4}Tremor{} on the main target) (max 4)",
                    "[I] {C:green}[On Hit]{} Inflict 1 {V:4}Tremor{}",
                    "[II] Spend 1 {V:1}Tigermark Round{}",
                    "{C:green}[On Hit]{} Inflict 2 {V:4}Tremor{}",
                    "{C:green}[On Hit]{} Inflict 2 {V:4}Burn{}",
                    "[III] Spend 1 {V:1}Tigermark Round{}",
                    "{C:green}[On Hit]{} Inflict +2 {V:4}Tremor{} Count",
                    "{C:green}[On Hit]{} Inflict +2 {V:4}Burn{} Count",
                    "{C:green}[On Hit]{} If target has 3+ {V:4}Tremor{} Count, trigger {V:4}Tremor Burst{}; then, reduce target's {V:4}Tremor{} Count by 1",
                },
            },
           
            j_star_notreadingallat_3         = { 
                name = 'Not Reading Allat',
                text = {
                    "Press {C:green}[C]{} to cycle description (4/7)",
                    " ",
                    "{C:red}Skill 3: Tanglecleaver{} (3 Coins, 5 Base Power, +4 Coin Power)",
                    "If this Joker has {V:1}Savage Tigermark Round{}, activate '{C:red}Savage Tigerslayer's Perfected Flurry of Blades{}' instead",
                    "Coin Power +1 for every 8 (sum of {V:4}Burn{} or {V:4}Tremor{} on the main target), (max 2)",
                    "[I] Spend 1 {V:1}Tigermark Round{}",
                    "{C:green}[On Hit]{} Inflict 3 {V:4}Tremor{}",
                    "{C:green}[On Hit]{} Inflict 3 {V:4}Burn{}",
                    "[II] Spend 1 {V:1}Tigermark Round{}",
                    "{C:green}[On Hit]{} Inflict +3 {V:4}Tremor{} Count",
                    "{C:green}[On Hit]{} Inflict +3 {V:4}Burn{} Count",
                    "[III] Spend 1 {V:1}Tigermark Round{}",
                    "If this unit spent {V:1}Tigermark Round{} due to this Coin's effect, deal +50% Damage",
                    "{C:green}[On Hit]{} Trigger Amplitude Conversion into {V:4}Tremor - Scorch{}",
                    "{C:green}[On Hit]{} Trigger {V:4}Tremor Burst{}; then, reduce target's {V:4}Tremor Count{} by 1",
                    "- When spending {V:1}Tigermark Round{}, activate the above effect 2 more times",
               },
            },
            j_star_notreadingallat_4         = { 
                name = 'Not Reading Allat',
                text = {
                    "Press {C:green}[C]{} to cycle description (5/7)",
                    " ",
                    "{C:red}Skill 3-2: Savage Tigerslayer's Perfected Flurry of Blades{} (5 Coins, 3 Base Power, +3 Coin Power)",
                    "Coin Power +1 for every 8 ({V:4}Burn{} + {V:4}Tremor{}) on the main target (max 2)",
                    "[I] {C:green}[On Hit]{} Inflict 3 {V:4}Tremor{}",
                    "[II] {C:green}[On Hit]{} Inflict +3 {V:4}Tremor{} Count",
                    "[III] Spend 1 {V:1}Savage Tigermark Round{}",
                    "{C:green}[On Hit]{} Inflict 3 {V:4}Burn{}",
                    "[IV] Spend 1 {V:1}Savage Tigermark Round{}",
                    "{C:green}[On Hit]{} Inflict +3 {V:4}Burn{} Count",
                    "[V] Spend 1 {V:1}Savage Tigermark Round{}",
                    "{C:green}[On Hit]{} Trigger Amplitude Conversion into {V:4}Tremor - Scorch{}",
                    "{C:green}[On Hit]{} Trigger {V:4}Tremor Burst{}; then, reduce target's {V:4}Tremor{} Count by 1",
                    "- When spending {V:1}Savage Tigermark Round{}, activate the above effect 2 more times",
                },
            },
            j_star_notreadingallat_5         = { 
                name = 'Not Reading Allat',
                text = {
                    "Press {C:green}[C]{} to cycle description (6/7)",
                    " ",
                    "{C:attention}Chachihu",
                  "Starts the Ante with 12 {V:1}Tigermark Round{}",
                  "When flipping a Coin that consumes {V:1}Tigermark Round{} or {V:1}Savage Tigermark Round{}: while not having those",
                  "'Unique Ammo' does not cancel this Joker's attacks, the Coin's On Hit 'inflict {V:4}Burn{}' and 'inflict",
                  "{V:4}Burn{} Count' effects do not activate",
                  "If this Joker spent all of his {V:1}Tigermark Round{}, reload 8 {V:1}Savage Tigermark Round{} and gain 1 Unrelenting Spirit",
                  "At 8+ (sum of {V:1}Tigermark Round{} and {V:1}Savage Tigermark Round{} spent),",
                  "convert Unrelenting Spirit to Unrelenting Spirit - Shin",
                  "After running out of {V:1}Savage Tigermark Round{}, gain 1 Overheat at end of hand",
                  " ",
                  "{C:attention}Tiantui Star's Blade",
                  "When this Joker has {V:1}Tigermark Round{}, Skill Coins that spend {V:1}Tigermark Round{} gain +1 power and deal",
                  "+10% damage (activates only as long as the Coin has Rounds left to spend)",
                  "When this Joker has {V:1}Savage Tigermark Round{}, Skill Coins that spend {V:1}Savage Tigermark Round{} gain +2 power,",
                  "deal +30% damage and inflict +2 more {V:4}Burn{} Potency and {V:4}Burn{} Count On Hit (activates only as long as the",
                  "Coin has Rounds left to spend)",
                },
            },
            j_star_notreadingallat_6         = { 
                name = 'Not Reading Allat',
                text = {
                    "Press {C:green}[C]{} to cycle description (7/7)",
                    " ",
                    "{V:4}Burn{}:",
                    "Multiply mult by {C:attention}#12#{}. Lasts {C:attention}#13#{} hand(s).",
                    " ",
                    "{V:4}Tremor{}:",
                    "When hit by attacks that trigger Tremor Burst, reduce blind's required score by {C:attention}#10#%{}. Lasts {C:attention}#11#{} hand(s).",
                    " ",
                    "{V:4}Tremor - Scorch{}:",
                    "On Tremor Burst, multiply Mult by (sum of Tremor Potency and Burn Potency / 2), and lose 1 Burn Count",
                    "When hit by attacks that trigger Tremor Burst, reduce blind's required score by {C:attention}#10#%{}. Lasts {C:attention}#11#{} hand(s).",
                    " ",
                    "{C:attention}Unrelenting Spirit:",
                    "Inflict +1 more Tremor Potency and Tremor Count with this Joker's Skills",
                    "If this Joker has spent 8+ (sum of {V:1}Tigermark Round{} and {V:1}Savage Tigermark Round{}): at hand",
                    "end, convert this buff to Unrelenting Spirit - Shin next hand",
                    "Max Stack: 1",
                    " ",
                    "{C:attention}Unrelenting Spirit - Shin:",
                    "Inflict +2 more Tremor Potency and Tremor Count with this Joker's Skills",
                    "Max Stack: 1",
                    " ",
                    "{C:diamonds}Overheat:",
                    "Loses this effect when this Joker gains {V:1}Savage Tigermark Round{}",
                    "Deal +(percentage of Hands used)% damage (max 50%)"
                },
            },
          
        }
    }
}